# Form implementation generated from reading ui file 'captcha2text_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 175)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.urlEdit = QtWidgets.QLineEdit(parent=Form)
        self.urlEdit.setObjectName("urlEdit")
        self.verticalLayout_4.addWidget(self.urlEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imgLable = QtWidgets.QLabel(parent=Form)
        self.imgLable.setMinimumSize(QtCore.QSize(30, 0))
        self.imgLable.setText("")
        self.imgLable.setObjectName("imgLable")
        self.horizontalLayout.addWidget(self.imgLable)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.identifyButton = QtWidgets.QPushButton(parent=Form)
        self.identifyButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.identifyButton.setObjectName("identifyButton")
        self.verticalLayout.addWidget(self.identifyButton)
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        self.textEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.identifyButton.clicked.connect(Form.identifyButton_click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "验证码识别 By SL03"))
        self.identifyButton.setText(_translate("Form", "识别"))
